[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "8Km1rYn4nDFpFpn3uPeDa2TLw3SBApJdHJKHoFnuQM7N"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
